Repository Project-MONAI/monai-deploy-storage, pull requests merged in 2022-11, with the labels that each got.

#109 Update licenses
  .github/workflows/ci.yml
  doc/dependency_decisions.yml
  third-party-licenses.md
Labels: build

#111 Release/0.2.9
  .github/workflows/ci.yml
  .github/workflows/package-cleanup.yml
  GitVersion.yml
  doc/dependency_decisions.yml
  src/Plugins/AWSS3/Monai.Deploy.Storage.AWSS3.csproj
  src/Plugins/MinIO/Monai.Deploy.Storage.MinIO.csproj
  src/Plugins/MinIO/Tests/Monai.Deploy.Storage.MinIO.Tests.csproj
  src/S3Policy/Tests/Monai.Deploy.Storage.S3Policy.Tests.csproj
  src/Storage/Monai.Deploy.Storage.csproj
  src/Storage/Tests/Monai.Deploy.Storage.Tests.csproj
  third-party-licenses.md
Labels: build

#112 Nds health check fix
  src/Plugins/AWSS3/StorageAdminService.cs
  src/Plugins/MinIO/MinIoAdminHealthCheck.cs
  src/Storage/API/IStorageAdminService.cs
Labels: bug

#114 Release/0.2.10
  .github/workflows/ci.yml
  GitVersion.yml
  src/Plugins/AWSS3/Monai.Deploy.Storage.AWSS3.csproj
  src/Plugins/AWSS3/StorageAdminService.cs
  src/Plugins/MinIO/MinIoAdminHealthCheck.cs
  src/Plugins/MinIO/Monai.Deploy.Storage.MinIO.csproj
  src/Storage/API/IStorageAdminService.cs
  src/Storage/Monai.Deploy.Storage.csproj
  third-party-licenses.md
Labels: build

#115 Sync Main branch
  .github/workflows/ci.yml
  GitVersion.yml
Labels: build

#133 Update packages
  doc/dependency_decisions.yml
  src/Plugins/AWSS3/Monai.Deploy.Storage.AWSS3.csproj
  src/Plugins/MinIO/Monai.Deploy.Storage.MinIO.csproj
  src/Storage/Monai.Deploy.Storage.csproj
  third-party-licenses.md
Labels: dependencies
